### PR TITLE
Setup rails api

### PR DESCRIPTION
**Pull request by akarmes**
## Status

**READY**
## Migrations

You have to setup database and create `config/database.yml`
## Description
- created `.ruby-version` and `.ruby-gemset`
- run `rails-api new . -T -d postgresql`
- added and initialized `rails-rspec`
## Steps to Test

```
$ git pull
$ git checkout setup-rails-api
$ bundle

setup database and change config/database.yml

$ bundle exec rake db:create
$ bundle exec rails s
```

### CODE REVIEW

**Comment by akarmes** [comment]
@isisAnchalee fixed

**Comment by wcjohnson11** [comment]
LGTM @90yukke :+1: 

I think we should add some "Getting up and running" notes to Readme.md for the non-backendy/ruby folks.

Below is what I had to do
1. Install [rbenv](https://github.com/sstephenson/rbenv)
2. `rbenv install 2.2.3`
3. `gem install bundler`
4. `gem install rails -v 4.2.4`
5. `rbenv rehash`
6. `cp config/database.yml.example config/database.yml`
7. `bundle install`
8. In Postgres Terminal `CREATE ROLE username SUPERUSER LOGIN`
8. `bundle exec rake db:create`
9. `rails s`

And the server was running :smile_cat:

**Comment by akarmes** [comment]
@wcjohnson11 feel free to send PR :)

Anyway, from my experience the problem with "How to setup app" guides is that people can use not only rvenv, but also rvm. And postgresql can be installed in different ways on both mac or linux. And then it always ends with maintaining of a guide with notes about all those postgresql/redis/node/mongo with brew/macports/apt-get/dpkg/complile_from_sources and further note about configuring on any possible platform.

**Comment by isisAnchalee** [comment]
I use rvm on one computer and rbenv on another. 
Also have done postgres via the app and CLI.
They're similar enough to figure out the nuances with strategic googling.
I do think a basic "how to get started" readme would be helpful considering some of the front-end talent has no real rails experience.

**Comment by akarmes** [comment]
@wcjohnson11 I updated readme with info about `rvm`. Hope you will add a similar section about `rbenv`.
@isisAnchalee How to get your thumb or fish or whatever? Since you have read this PR already :smile:

**Comment by isisAnchalee** [comment]
:+1: :rabbit:

**Pull request merged**
